//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm
    {
        public alarm()
        {
            this.alarmconditions = new HashSet<alarmcondition>();
            this.alarmhistories = new HashSet<alarmhistory>();
        }
    
        public long id { get; set; }
        public long meterid { get; set; }
        public string alarmname { get; set; }
        public string message { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual ICollection<alarmcondition> alarmconditions { get; set; }
        public virtual ICollection<alarmhistory> alarmhistories { get; set; }
        public virtual meter meter { get; set; }
    }
}
