//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class blockaddressdetail
    {
        public long id { get; set; }
        public long modelid { get; set; }
        public long blockrangeid { get; set; }
        public string address { get; set; }
        public string parametername { get; set; }
        public string datatype { get; set; }
        public string loadservicemapping { get; set; }
        public Nullable<double> multiplicationfactor { get; set; }
        public string tablename { get; set; }
        public string grouptype { get; set; }
    
        public virtual metermodel metermodel { get; set; }
        public virtual blockranx blockranx { get; set; }
    }
}
