//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class blockranx
    {
        public blockranx()
        {
            this.blockaddressdetails = new HashSet<blockaddressdetail>();
        }
    
        public long id { get; set; }
        public long modelid { get; set; }
        public string blocktype { get; set; }
        public string currentblockaddress { get; set; }
        public string previousblockaddress { get; set; }
        public string isincremental { get; set; }
        public string noofregisters { get; set; }
    
        public virtual ICollection<blockaddressdetail> blockaddressdetails { get; set; }
        public virtual metermodel metermodel { get; set; }
    }
}
