//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class communicationdetail
    {
        public communicationdetail()
        {
            this.communicationdetaillinks = new HashSet<communicationdetaillink>();
        }
    
        public long id { get; set; }
        public long communicationtypeid { get; set; }
        public string ipaddress { get; set; }
        public string port { get; set; }
        public string baudrate { get; set; }
        public string databits { get; set; }
        public string parity { get; set; }
        public string stopbits { get; set; }
        public string convertordesc { get; set; }
        public string comport { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public Nullable<short> isactive { get; set; }
        public Nullable<short> isemailalarm { get; set; }
        public Nullable<short> ispopupalarm { get; set; }
        public Nullable<short> isalarmraised { get; set; }
        public Nullable<short> issmsalarm { get; set; }
    
        public virtual ICollection<communicationdetaillink> communicationdetaillinks { get; set; }
    }
}
