//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumer
    {
        public long id { get; set; }
        public string masterid { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string billingunitid { get; set; }
        public string classid { get; set; }
        public long categoryid { get; set; }
        public string userid { get; set; }
        public string gender { get; set; }
        public string maritalstatus { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string landline { get; set; }
        public string mobile { get; set; }
        public string emailid { get; set; }
        public string education { get; set; }
        public string incomerange { get; set; }
        public string occupation { get; set; }
        public string companyname { get; set; }
        public string contactperson { get; set; }
        public Nullable<System.DateTime> incorporationdate { get; set; }
        public string incorporationtype { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public string type { get; set; }
    
        public virtual consumercategory consumercategory { get; set; }
    }
}
