//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumercategory
    {
        public consumercategory()
        {
            this.consumers = new HashSet<consumer>();
        }
    
        public long categoryrecid { get; set; }
        public string categoryid { get; set; }
        public string categorydescription { get; set; }
        public string categorytariffid { get; set; }
        public Nullable<short> categoryisdeleted { get; set; }
        public Nullable<int> categoryfixedstatus { get; set; }
    
        public virtual ICollection<consumer> consumers { get; set; }
    }
}
