//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactdetail
    {
        public long id { get; set; }
        public string emailaddress { get; set; }
        public Nullable<long> phonenumber { get; set; }
        public Nullable<short> isdeleted { get; set; }
    }
}
