//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcsg
    {
        public long id { get; set; }
        public Nullable<long> blockno { get; set; }
        public Nullable<decimal> dcvalue { get; set; }
        public Nullable<decimal> sgvalue { get; set; }
        public Nullable<int> revision { get; set; }
        public Nullable<long> timestampid { get; set; }
        public Nullable<decimal> fuelcost { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<long> stageid { get; set; }
        public System.DateTime upload_date { get; set; }
        public Nullable<decimal> sgppa { get; set; }
        public Nullable<decimal> sced { get; set; }
        public Nullable<decimal> rras { get; set; }
        public Nullable<decimal> agc { get; set; }
        public decimal iex { get; set; }
        public decimal urs { get; set; }
    }
}
