//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dowrite
    {
        public long id { get; set; }
        public long meterid { get; set; }
        public Nullable<double> memoryadd { get; set; }
        public Nullable<double> flag { get; set; }
        public Nullable<int> isactive { get; set; }
    }
}
