//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailconfigdetail
    {
        public long row_id { get; set; }
        public string emprecid { get; set; }
        public string maildetails { get; set; }
        public Nullable<int> sendflag { get; set; }
    }
}
