//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class emaildetail
    {
        public long recid { get; set; }
        public string maillist { get; set; }
        public string filepath { get; set; }
        public string subject { get; set; }
        public string mailbody { get; set; }
        public Nullable<int> sendflag { get; set; }
    }
}
