//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class evt_30secdatalogs
    {
        public long meterid { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<double> t_vrn { get; set; }
        public Nullable<double> t_vbn { get; set; }
        public Nullable<double> t_vyn { get; set; }
        public Nullable<double> t_vln { get; set; }
        public Nullable<double> t_vry { get; set; }
        public Nullable<double> t_vyb { get; set; }
        public Nullable<double> t_vbr { get; set; }
        public Nullable<double> t_vll { get; set; }
        public Nullable<double> t_ir { get; set; }
        public Nullable<double> t_iy { get; set; }
        public Nullable<double> t_ib { get; set; }
        public Nullable<double> t_i { get; set; }
        public Nullable<double> t_pf { get; set; }
        public Nullable<double> t_kw { get; set; }
        public Nullable<double> t_kvar { get; set; }
        public Nullable<double> t_kva { get; set; }
        public Nullable<double> t_hz { get; set; }
    }
}
