//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class htalarm
    {
        public long id { get; set; }
        public Nullable<long> timestampid { get; set; }
        public string type { get; set; }
        public Nullable<short> isactive { get; set; }
        public string hostip { get; set; }
        public string alarmname { get; set; }
        public string alarmmessage { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<short> sms { get; set; }
        public Nullable<short> email { get; set; }
        public Nullable<short> popup { get; set; }
        public Nullable<long> alarmid { get; set; }
        public Nullable<short> ismanualack { get; set; }
    }
}
