//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class instancedatado
    {
        public long id { get; set; }
        public long meterid { get; set; }
        public string meter_name { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<double> do1 { get; set; }
        public Nullable<double> do2 { get; set; }
        public Nullable<double> do3 { get; set; }
        public Nullable<double> do4 { get; set; }
        public Nullable<double> do5 { get; set; }
        public Nullable<double> do6 { get; set; }
        public Nullable<double> do7 { get; set; }
        public Nullable<double> do8 { get; set; }
        public Nullable<double> do9 { get; set; }
        public Nullable<double> do10 { get; set; }
        public Nullable<double> do11 { get; set; }
        public Nullable<double> do12 { get; set; }
        public Nullable<double> do13 { get; set; }
        public Nullable<double> do14 { get; set; }
        public Nullable<double> do15 { get; set; }
        public Nullable<double> do16 { get; set; }
    }
}
