//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class instancedatadi
    {
        public long id { get; set; }
        public long meterid { get; set; }
        public string meter_name { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<double> di1 { get; set; }
        public Nullable<double> di2 { get; set; }
        public Nullable<double> di3 { get; set; }
        public Nullable<double> di4 { get; set; }
        public Nullable<double> di5 { get; set; }
        public Nullable<double> di6 { get; set; }
        public Nullable<double> di7 { get; set; }
        public Nullable<double> di8 { get; set; }
        public Nullable<double> di9 { get; set; }
        public Nullable<double> di10 { get; set; }
        public Nullable<double> di11 { get; set; }
        public Nullable<double> di12 { get; set; }
        public Nullable<double> di13 { get; set; }
        public Nullable<double> di14 { get; set; }
        public Nullable<double> di15 { get; set; }
        public Nullable<double> di16 { get; set; }
        public Nullable<double> di17 { get; set; }
        public Nullable<double> di18 { get; set; }
        public Nullable<double> di19 { get; set; }
        public Nullable<double> di20 { get; set; }
        public Nullable<double> di21 { get; set; }
        public Nullable<double> di22 { get; set; }
        public Nullable<double> di23 { get; set; }
        public Nullable<double> di24 { get; set; }
        public Nullable<double> di25 { get; set; }
        public Nullable<double> di26 { get; set; }
        public Nullable<double> di27 { get; set; }
        public Nullable<double> di28 { get; set; }
        public Nullable<double> di29 { get; set; }
        public Nullable<double> di30 { get; set; }
        public Nullable<double> di31 { get; set; }
        public Nullable<double> di32 { get; set; }
    }
}
