//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class instancedata
    {
        public long id { get; set; }
        public long meterid { get; set; }
        public string meter_name { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<double> vrn { get; set; }
        public Nullable<double> vbn { get; set; }
        public Nullable<double> vyn { get; set; }
        public Nullable<double> vln { get; set; }
        public Nullable<double> vry { get; set; }
        public Nullable<double> vyb { get; set; }
        public Nullable<double> vbr { get; set; }
        public Nullable<double> vll { get; set; }
        public Nullable<double> ir { get; set; }
        public Nullable<double> iy { get; set; }
        public Nullable<double> ib { get; set; }
        public Nullable<double> i { get; set; }
        public Nullable<double> pf { get; set; }
        public Nullable<double> kw { get; set; }
        public Nullable<double> kvar { get; set; }
        public Nullable<double> kva { get; set; }
        public Nullable<double> hz { get; set; }
        public Nullable<double> pfr { get; set; }
        public Nullable<double> pfy { get; set; }
        public Nullable<double> pfb { get; set; }
        public Nullable<double> kwr { get; set; }
        public Nullable<double> kwy { get; set; }
        public Nullable<double> kwb { get; set; }
        public Nullable<double> kvarr { get; set; }
        public Nullable<double> kvary { get; set; }
        public Nullable<double> kvarb { get; set; }
        public Nullable<double> kva_r { get; set; }
        public Nullable<double> kvay { get; set; }
        public Nullable<double> kvab { get; set; }
        public Nullable<double> kw_demand { get; set; }
        public Nullable<double> kvar_demand { get; set; }
        public Nullable<double> kva_demand { get; set; }
        public Nullable<double> kw_max_demand { get; set; }
        public Nullable<double> kvar_max_demand { get; set; }
        public Nullable<double> kva_max_demand { get; set; }
        public Nullable<double> kwh_exp { get; set; }
        public Nullable<double> kwh_imp { get; set; }
        public Nullable<double> kvah_exp { get; set; }
        public Nullable<double> kvah_imp { get; set; }
        public Nullable<double> kvarh_lag_imp { get; set; }
        public Nullable<double> kvarh_lead_imp { get; set; }
        public Nullable<double> kvarh_lag_exp { get; set; }
        public Nullable<double> kvarh_lead_exp { get; set; }
        public Nullable<double> kvarh_exp_103 { get; set; }
        public Nullable<double> kvarh_exp_97 { get; set; }
        public Nullable<double> kvarh_imp_103 { get; set; }
        public Nullable<double> kvarh_imp_97 { get; set; }
        public Nullable<double> day_kwh_exp { get; set; }
        public Nullable<double> day_kwh_imp { get; set; }
        public Nullable<double> cblk_kwh_exp { get; set; }
        public Nullable<double> cblk_kwh_imp { get; set; }
        public Nullable<double> cblk_kvarh_lag_imp { get; set; }
        public Nullable<double> cblk_kvarh_lead_imp { get; set; }
        public Nullable<double> cblk_kvarh_lag_exp { get; set; }
        public Nullable<double> cblk_kvarh_lead_exp { get; set; }
        public Nullable<double> cblk_avg_mw { get; set; }
        public Nullable<double> cblk_avg_hz { get; set; }
        public Nullable<double> lblk_timestampid { get; set; }
        public Nullable<double> lblk_avg_mw { get; set; }
        public Nullable<double> lblk_avg_hz { get; set; }
        public Nullable<double> lblk_kwh_exp { get; set; }
        public Nullable<double> lblk_kwh_imp { get; set; }
        public Nullable<double> lblk_kvah_exp { get; set; }
        public Nullable<double> lblk_kvah_imp { get; set; }
        public Nullable<double> lblk_kvarh_lag_imp { get; set; }
        public Nullable<double> lblk_kvarh_lead_imp { get; set; }
        public Nullable<double> lblk_kvarh_lag_exp { get; set; }
        public Nullable<double> lblk_kvarh_lead_exp { get; set; }
        public Nullable<double> lblk_kvarh_exp_103 { get; set; }
        public Nullable<double> lblk_kvarh_exp_97 { get; set; }
        public Nullable<double> lblk_kvarh_imp_103 { get; set; }
        public Nullable<double> lblk_kvarh_imp_97 { get; set; }
        public Nullable<double> potime { get; set; }
        public Nullable<double> lotime { get; set; }
        public Nullable<double> kwh_net { get; set; }
        public Nullable<int> temp { get; set; }
        public Nullable<double> runhrimp { get; set; }
        public Nullable<double> runhrexp { get; set; }
        public Nullable<System.DateTime> meter_tstamp { get; set; }
    }
}
