//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class manualreport
    {
        public long reptmid { get; set; }
        public long rlistid { get; set; }
        public System.DateTime requestdate { get; set; }
        public System.DateTime frmdate { get; set; }
        public string frmtime { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public string totime { get; set; }
        public string filepath { get; set; }
        public Nullable<int> isdownload { get; set; }
    
        public virtual manualrptlist manualrptlist { get; set; }
    }
}
