//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class memorymap_range
    {
        public memorymap_range()
        {
            this.memorymap_addressdetails = new HashSet<memorymap_addressdetails>();
        }
    
        public long id { get; set; }
        public long modelid { get; set; }
        public string startaddress { get; set; }
        public string endaddress { get; set; }
        public string countaddress { get; set; }
        public string rangetype { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public string types { get; set; }
    
        public virtual ICollection<memorymap_addressdetails> memorymap_addressdetails { get; set; }
        public virtual metermodel metermodel { get; set; }
    }
}
