//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class metergroup
    {
        public metergroup()
        {
            this.groupconfigurations = new HashSet<groupconfiguration>();
            this.mstmetergroupdetails = new HashSet<mstmetergroupdetail>();
        }
    
        public long id { get; set; }
        public string groupname { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual ICollection<groupconfiguration> groupconfigurations { get; set; }
        public virtual ICollection<mstmetergroupdetail> mstmetergroupdetails { get; set; }
    }
}
