//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class metertype
    {
        public metertype()
        {
            this.meters = new HashSet<meter>();
        }
    
        public long id { get; set; }
        public string metertypename { get; set; }
        public string meterdescription { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual ICollection<meter> meters { get; set; }
    }
}
