//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class metermodel
    {
        public metermodel()
        {
            this.blockaddressdetails = new HashSet<blockaddressdetail>();
            this.blockranges = new HashSet<blockranx>();
            this.memorymap_addressdetails = new HashSet<memorymap_addressdetails>();
            this.memorymap_range = new HashSet<memorymap_range>();
            this.meters = new HashSet<meter>();
        }
    
        public long id { get; set; }
        public string modelname { get; set; }
        public string description { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public Nullable<long> rolloverlimit { get; set; }
        public Nullable<short> connecttime { get; set; }
        public Nullable<short> senddonewait { get; set; }
        public Nullable<short> waitconsecutive { get; set; }
        public Nullable<short> onresponceerror { get; set; }
    
        public virtual ICollection<blockaddressdetail> blockaddressdetails { get; set; }
        public virtual ICollection<blockranx> blockranges { get; set; }
        public virtual ICollection<memorymap_addressdetails> memorymap_addressdetails { get; set; }
        public virtual ICollection<memorymap_range> memorymap_range { get; set; }
        public virtual ICollection<meter> meters { get; set; }
    }
}
