//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstdivision
    {
        public mstdivision()
        {
            this.mstsubstations = new HashSet<mstsubstation>();
        }
    
        public long divrecid { get; set; }
        public string divid { get; set; }
        public string divname { get; set; }
        public string divdescription { get; set; }
        public Nullable<long> divrgnid { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual mstregion mstregion { get; set; }
        public virtual ICollection<mstsubstation> mstsubstations { get; set; }
    }
}
