//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class msterrorlog
    {
        public long errorid { get; set; }
        public string errordescription { get; set; }
        public string errortrace { get; set; }
        public string errormodule { get; set; }
        public Nullable<System.DateTime> errordate { get; set; }
    }
}
