//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstemployee
    {
        public long emprecid { get; set; }
        public string empid { get; set; }
        public string empfirstname { get; set; }
        public string empmiddlename { get; set; }
        public string emplastname { get; set; }
        public string empzoneid { get; set; }
        public string emprgnid { get; set; }
        public string empdivid { get; set; }
        public string empsubstnid { get; set; }
        public Nullable<short> empisactive { get; set; }
        public string empemailid { get; set; }
        public string empphoneno1 { get; set; }
        public string empphoneno2 { get; set; }
        public Nullable<short> empisdeleted { get; set; }
    }
}
