//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstfeeder
    {
        public long fdrrecid { get; set; }
        public string fdrid { get; set; }
        public string fdrname { get; set; }
        public string fdrdescription { get; set; }
        public string fdrserialno { get; set; }
        public Nullable<decimal> fdrratedvoltage { get; set; }
        public Nullable<decimal> fdrratedpower { get; set; }
        public Nullable<decimal> fdrconnectedload { get; set; }
        public string fdrphase { get; set; }
        public string fdrmanufacturerid { get; set; }
        public string fdrsubstnid { get; set; }
        public string fdrinstallarea { get; set; }
        public Nullable<short> fdrisdeleted { get; set; }
    }
}
