//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstholiday
    {
        public long holrecid { get; set; }
        public string holid { get; set; }
        public string holdescription { get; set; }
        public Nullable<System.DateTime> holdate { get; set; }
        public Nullable<System.DateTime> hollegaldate { get; set; }
        public Nullable<short> holisdeleted { get; set; }
    }
}
