//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstrole
    {
        public mstrole()
        {
            this.mstusers = new HashSet<mstuser>();
            this.mstrolemenuaccesses = new HashSet<mstrolemenuaccess>();
        }
    
        public long rolrecid { get; set; }
        public string rolname { get; set; }
        public string roldescription { get; set; }
        public Nullable<short> rolisdeleted { get; set; }
    
        public virtual ICollection<mstuser> mstusers { get; set; }
        public virtual ICollection<mstrolemenuaccess> mstrolemenuaccesses { get; set; }
    }
}
