//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstregion
    {
        public mstregion()
        {
            this.mstdivisions = new HashSet<mstdivision>();
        }
    
        public long rgnrecid { get; set; }
        public string rgnid { get; set; }
        public string rgnname { get; set; }
        public string rgndescription { get; set; }
        public Nullable<long> rgnznid { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual ICollection<mstdivision> mstdivisions { get; set; }
        public virtual mstzone mstzone { get; set; }
    }
}
