//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstrolemenuaccess
    {
        public long rmarecid { get; set; }
        public Nullable<long> rmaroleid { get; set; }
        public Nullable<long> rmamnuid { get; set; }
        public Nullable<short> rmacreateaccess { get; set; }
        public Nullable<short> rmareadaccess { get; set; }
        public Nullable<short> rmaupdateaccess { get; set; }
        public Nullable<short> rmadeleteaccess { get; set; }
        public Nullable<short> rmaisdeleted { get; set; }
    
        public virtual mstmenu mstmenu { get; set; }
        public virtual mstrole mstrole { get; set; }
    }
}
