//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstsubstation
    {
        public long ssrecid { get; set; }
        public string ssid { get; set; }
        public string ssname { get; set; }
        public string ssdescription { get; set; }
        public Nullable<long> ssdivid { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual mstdivision mstdivision { get; set; }
    }
}
