//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstzone
    {
        public mstzone()
        {
            this.mstregions = new HashSet<mstregion>();
        }
    
        public long znrecid { get; set; }
        public string znid { get; set; }
        public string znname { get; set; }
        public string zndescription { get; set; }
        public Nullable<long> znutilityid { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual ICollection<mstregion> mstregions { get; set; }
        public virtual mstutility mstutility { get; set; }
    }
}
