//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class opc_clienttag
    {
        public long id { get; set; }
        public Nullable<int> tag_id { get; set; }
        public string tag_name { get; set; }
        public string caltype { get; set; }
    }
}
