//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class opc_server_tag
    {
        public long id { get; set; }
        public string tagname { get; set; }
        public string datatype { get; set; }
        public Nullable<long> meterid { get; set; }
        public string parameter { get; set; }
        public string tablename { get; set; }
        public string query { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<long> istag { get; set; }
        public Nullable<long> priority { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
    }
}
