//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcloadsurveylog
    {
        public long tagid { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<int> timestampid { get; set; }
        public Nullable<int> blockno { get; set; }
        public Nullable<double> tagvalue { get; set; }
    }
}
