//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class prmglobal
    {
        public long prmrecid { get; set; }
        public string prmmodule { get; set; }
        public string prmunit { get; set; }
        public string prmidentifier { get; set; }
        public string prmvalue { get; set; }
        public string rfu1 { get; set; }
        public string rfu2 { get; set; }
    }
}
