//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class querydetail
    {
        public long id { get; set; }
        public string queryname { get; set; }
        public string property { get; set; }
        public string setvalue { get; set; }
        public string script { get; set; }
    }
}
