//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtalarm
    {
        public long id { get; set; }
        public string alarmname { get; set; }
        public string alarmmessage { get; set; }
        public Nullable<System.DateTime> fromtime { get; set; }
        public Nullable<System.DateTime> totime { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> resetstatus { get; set; }
        public string alarmquery { get; set; }
        public string condition { get; set; }
        public string alarmcommand { get; set; }
        public string meterid { get; set; }
        public Nullable<short> sendsms { get; set; }
        public Nullable<short> sendemail { get; set; }
        public Nullable<short> givepopup { get; set; }
        public string parameter { get; set; }
        public Nullable<short> isdeleted { get; set; }
    }
}
