//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageconfiguration
    {
        public long id { get; set; }
        public string stagename { get; set; }
        public string stagenmfrmupload { get; set; }
        public string generator { get; set; }
        public string linemeter { get; set; }
    }
}
