//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class standardalarm
    {
        public long id { get; set; }
        public long meterid { get; set; }
        public Nullable<double> maxvll { get; set; }
        public Nullable<double> minvll { get; set; }
        public Nullable<double> maxamp { get; set; }
        public Nullable<double> minamp { get; set; }
        public Nullable<double> maxkw { get; set; }
        public Nullable<double> minkw { get; set; }
        public Nullable<double> maxkva { get; set; }
        public Nullable<double> minkva { get; set; }
        public Nullable<double> maxhz { get; set; }
        public Nullable<double> minhz { get; set; }
        public Nullable<double> maxpf { get; set; }
        public Nullable<double> minpf { get; set; }
        public Nullable<double> connectload { get; set; }
        public string alarmmessages { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> resetstatus { get; set; }
        public Nullable<int> duration { get; set; }
        public string alarmcommand { get; set; }
        public Nullable<short> sendsms { get; set; }
        public Nullable<short> sendemail { get; set; }
        public Nullable<short> givepopup { get; set; }
        public string alarmname { get; set; }
        public Nullable<short> isdeleted { get; set; }
    
        public virtual meter meter { get; set; }
    }
}
