//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablewiseparameter
    {
        public long id { get; set; }
        public string parametername { get; set; }
        public string tablename { get; set; }
        public Nullable<short> isdeleted { get; set; }
    }
}
