//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class uirate
    {
        public long id { get; set; }
        public Nullable<decimal> frequency { get; set; }
        public Nullable<decimal> positive { get; set; }
        public Nullable<decimal> negative { get; set; }
        public System.DateTime tstamp { get; set; }
        public Nullable<int> revision { get; set; }
        public Nullable<int> stageid { get; set; }
        public Nullable<short> isdeleted { get; set; }
        public System.DateTime upload_date { get; set; }
    }
}
